version: "3.8"
services:
  rabbitmq3:
    container_name: "rabbitmq"
    build: ../
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
      - '5671:5671'
    volumes:
      - /home/sebastian/IdeaProjects/kafka-ssl-compose/secrets/broker.keystore.jks:/etc/certs/broker.keystore.jks
      - /home/sebastian/IdeaProjects/kafka-ssl-compose/secrets/broker.truststore.jks:/etc/certs/broker.truststore.jks
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
networks:
  brokers_app_network:
    external: true