version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${ROOT_POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${ROOT_POSTGRES_USER}
      - POSTGRES_DB=kafka_db
    networks:
      - brokers_app_network

networks:
  brokers_app_network:
    external: true