server.port: 8081

common:
  modes:
    producerMode: true
    consumerMode: true
  topic:
    config:
      number-of-partitions: 5
      replication-factor: 1
      topic-name: STRING-TOPIC2
      concurrency: 5
      load-size: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka_db
    username: clm
    password: ENC(Eh6ysCOM8cFm2dC0flEOLPKR0vOrp3T3cTHLGgZVB+cTfZHH3jqoWsp/t89M4N22)
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    client-id: kafka_test
    consumer:
      group-id: kafka_test_group
      value-deserializer: org.apache.kafka.common.serialization.BytesDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 10
    producer:
      batch-size: 2000
  cloud:
      function:
        definition: consumerMethod
      stream:
        bindings:
          senderMethod-out-0:
            producer:
              partitionKeyExtractorName: headers.id
              partitionCount: ${common.topic.config.number-of-partitions}
            destination: ${common.topic.config.topic-name}
          consumerMethod-in-0:
            destination: ${common.topic.config.topic-name}
            consumer:
              concurrency: 5



  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQL82Dialect
  pulsar:
    client:
      service-url: pulsar://localhost:6650
      defaults:
        type-mappings:
          - message-type: com.example.kafka_demo.dto.DefaultSchema
            schema-info:
              schema-type: JSON

jasypt:
  encryptor:
    password: ${ENCRYPTOR_PASSWORD}
    algorithm: "PBEWITHHMACSHA512ANDAES_256"
    salt-generator-classname: "org.jasypt.salt.RandomSaltGenerator"
    iv-generator-classname: "org.jasypt.iv.RandomIvGenerator"
    provider-name: "SunJCE"
    string-output-type: "base64"
    pool-size: 1
    key-obtention-iterations: 1000

